name: tests

on: [push, pull_request]

jobs:
 test:
  runs-on: ubuntu-latest

  strategy:
   fail-fast: true
   matrix:
    php: [8.5, 8.4, 8.3]
    laravel: ["^13", "^12"]
    dependency-version: [prefer-lowest, prefer-stable]
    include:
     - laravel: "^13"
       testbench: 11.*
     - laravel: "^12"
       testbench: 10.*

  name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup PHP
     uses: shivammathur/setup-php@v2
     with:
      php-version: ${{ matrix.php }}
      extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
      coverage: none

   - name: Install dependencies
     run: |
      composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
      composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

   - name: Execute tests
     run: vendor/bin/phpunit
